version: '3.1'

volumes:
    grafana_data: {}

services:

  mqtt2influx:
    build:
      context: ./mqtt2influx/
      dockerfile: Dockerfile
    network_mode: host
  grafana:
    build:
      context: ./grafana/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.env
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb:1.7
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=connectedlabdata
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
